[general]
import = [
    "~/.config/alacritty/themes/themes/catppuccin_macchiato.toml",
    "~/.config/alacritty/keybindings.toml"
]
live_config_reload = true

[font]
size = 11.0
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }

[window]
  option_as_alt="Both"
  opacity=1.0
  startup_mode="Windowed"
  decorations="None"
  blur=true
  padding = { x = 5, y = 0 }
